title: "@rzlslch"
email: rizal.solichudin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: '' # the subpath of your site, e.g. /blog
url: 'rzlslch.github.io' # the base hostname & protocol for your site, e.g. http://example.com 
github_username:  rzlslch

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: css